### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by etobella** [tegin/cb-maintenance#11]
They should be on equipments too and location of the request should be the same of the equipment (onchange + readonly + write - create???)

**Comment by jarroyomorales** [comment]
Should be the same or at least be child of that yes. But how do we do it? Is the equipment location what gives location to requests? I think it is. A user can enter a location, but later, if a technician assigns the request to an equipment, its location should be written to the request.
And another problem is that we must guarantee that all equipments have their correct location and this info must be properly maintaned, which is not easy, otherwise this can be a disaster.
